### ISSUE TITLE
[PE-D][Tester D] Add command allows numbers to be used as names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#114]
![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/7ac3e9a7-cdd6-4bd1-832e-9f28844d0a2b.png)

Names should not be a number.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: justinlengch/ped#12

**Comment by blaukc** [comment]
Feature change
