### ISSUE TITLE
[PE-D][Tester D] GUI cut off with long names

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#116]
![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/2587f7cc-7be2-46b8-a272-a3144c9cc62c.png)

As shown above, instead should try to make it work by letting it create a new line.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: justinlengch/ped#14

**Comment by AdityaB4** [comment]
@yadunut do you want to fix this one with input validation?

**Comment by yadunut** [comment]
Would it be safe to just limit name lengths to 255 characters? Also as part of our future fixes section, we should say we're working on adding support for names with non-alphanumeric characters and right to left languages, such as arabic. As of now, we only support English names with a max length of 255 characters

**Comment by blaukc** [comment]
Feature change
