### ISSUE TITLE
[PE-D][Tester D] User Guide potential issue with image loading

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#119]
![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/5e53e06f-2623-4764-ae00-980d6ae830af.png)
the word "IMAGES." seems out of place. Perhaps it was a placeholder for an image but it is not loaded in.

Also note the word probably in the image above, it suggests that the entire paragraph for Usage is more of a text placeholder to be replaced with actual texts but was not filled. This leads to confusion for the reader.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: justinlengch/ped#17

**Comment by AdityaB4** [comment]
@taufiq have you fixed this already?
