### ISSUE TITLE
[PE-D][Tester D] Quick Start guide does not work for MacOS users

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#120]
![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/1909cdc7-180a-4633-91e3-39f694e04881.png)

MacOS users cannot open modcontacts.jar with the method above, they can only open it in a terminal.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: justinlengch/ped#18

**Comment by blaukc** [comment]
skill issue.
