### ISSUE TITLE
[PE-D][Tester B] Exception command doesn't indicate invalid time problem accurately

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#73]
![image.png](https://raw.githubusercontent.com/Hwww23/ped/main/files/f4fa9c2d-b176-4f61-89ce-a645de433520.png)

The message user receives can be more specific, e.g. "Please key in a valid time"

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Hwww23/ped#3

**Comment by AdityaB4** [comment]
Note: it is 13am in the screenshot.

**Comment by blaukc** [comment]
Feature change
