### ISSUE TITLE
[PE-D][Tester A] Command summary missing new commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#74]
The command summary is missing the commands for add_module, delete_module, add_timing, delete_timing, find_free_time, list_modules and module_search.

![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/4da09e2f-288a-4813-a1ee-d3e0a8adca6e.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: DominicFuMJ/ped#2

**Comment by blaukc** [comment]
fixed
