### ISSUE TITLE
[PE-D][Tester A] Tag is unable to accept string with space inside

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#82]
When attempting to edit or add a student with a tag, it does not accept tags with spacing inbetween them.
![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/25cd534d-f55e-40e8-a7da-4f87a0b9da44.png)

![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/4121e3d6-40c2-4b20-84c3-990f32800ad0.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: DominicFuMJ/ped#3

**Comment by AdityaB4** [comment]
Documentation can mention use of underscore in favour of whitespace.
