### ISSUE TITLE
[PE-D][Tester D] User guide example command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#89]
![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/8cc04e63-1f2f-4f2e-96c4-480cc0ac2105.png)

![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/915be625-3a0c-4543-bf4f-af7a181fa81b.png)

it appears that the example add command at the start of the UG has a different format than the in-depth explanation one in features.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: justinlengch/ped#5

**Comment by AdityaB4** [comment]
Related to #37 and #98.

**Comment by blaukc** [comment]
Closed in https://github.com/AY2324S2-CS2103T-W12-2/tp/pull/152
