### ISSUE TITLE
[PE-D][Tester A] list_modules has no example and is confusing.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#90]
![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/82a0f070-474f-43af-9c4d-8d3877d6c5a8.png)
There is no example for the list_modules command.
The list_modules is very short and confusing as there is no code to add information for the modules.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: DominicFuMJ/ped#5

**Comment by AdityaB4** [comment]
Not really a bug since its not a necessity to have detailed guides for each command. Assigned low priority for now but we can re-evaluate in a couple of days.

**Comment by yadunut** [comment]
Closed by #143
