### ISSUE TITLE
[PE-D][Tester B] No real use of some parameters in add format

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#93]
![image.png](https://raw.githubusercontent.com/Hwww23/ped/main/files/a9723437-3cd1-45c6-b36a-f9b5e4d3faa6.png)

![image.png](https://raw.githubusercontent.com/Hwww23/ped/main/files/e88f7d31-010d-4f58-93ec-167e4a1ae288.png)

add n/Ben p/98765432 e/ben@gmail.com a/eunos successfully adds, however,  only name and phone number are seen while the other parameters are hidden. This makes users need to put extra effort into keying in redundant information that will not be utilized or shown to them.

![image.png](https://raw.githubusercontent.com/Hwww23/ped/main/files/6df08b5c-bb62-4014-97b1-4ac1a002f7e3.png)

In addition, "add n/chris p/98764321 e/gg@gmail.com a/eunos t/friends", does not seem to show any tags as well.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Hwww23/ped#8

**Comment by AdityaB4** [comment]
Subset of #37 and #98. Accepted but closing.
