### ISSUE TITLE
[PE-D][Tester D] Parameters for adding student not shown in UI

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#98]
![image.png](https://raw.githubusercontent.com/justinlengch/ped/main/files/65076eb4-9c73-46a8-ac71-fdafa659fa01.png)

All the different not optional parameters required when adding a new student does not show up on student list. This makes the parameters such as address etc unnecessary as it is not used anywhere in the application.

Suggestion to not require these parameters that are not used.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: justinlengch/ped#7

**Comment by AdityaB4** [comment]
This is related to #37.

**Comment by AdityaB4** [comment]
@AY2324S2-CS2103T-W12-2/developers would this be considered a [feature flaw](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#feature-flaws-2)?

If yes, this'll end up being a documentation fix instead. See [Planned Enhancements](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-w12.html#2-start-fixing-ped-bugs-before-the-tutorial).

**Comment by AdityaB4** [comment]
This issue and #37 are related to the `view_x` planned enhancement, and will be worked upon as a documentation bug instead. Tracking this in #130 and closing the 2 original issues.
